// Vercel static-build step for the PointsX frontend repo.
//
// Repo layout:
//   static/                       ← the SPA as authored
//     index.html
//     config.js                   ← rewritten with runtime POINTSX_API_BASE
//     css/...
//     js/...
//
// What this script writes:
//   public/
//     index.html                  ← copied from static/index.html
//     static/                     ← copied from static/ (all assets)
//       config.js                 ← OVERWRITTEN with the runtime POINTSX_API_BASE
//       css/...
//       js/...
//
// Required env var on Vercel:
//   POINTSX_API_BASE   e.g. https://your-username-pointsx-backend.hf.space

import { cp, mkdir, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "static");
const OUT = path.join(ROOT, "public");
const OUT_STATIC = path.join(OUT, "static");

const apiBase = (process.env.POINTSX_API_BASE || "").replace(/\/+$/, "");

await mkdir(OUT, { recursive: true });
await mkdir(OUT_STATIC, { recursive: true });

// 1. Copy everything from static/ into public/static/
await cp(SRC, OUT_STATIC, { recursive: true });

// 2. Promote index.html to the site root
await copyFile(path.join(SRC, "index.html"), path.join(OUT, "index.html"));

// 3. Overwrite config.js with the runtime API base (POINTSX_API_BASE env var)
const configJs = [
  "// AUTO-GENERATED by scripts/build_static.mjs at Vercel build time.",
  "// Edit POINTSX_API_BASE in the Vercel project's env vars to change.",
  `window.POINTSX_API_BASE = ${JSON.stringify(apiBase)};`,
  "",
].join("\n");
await writeFile(path.join(OUT_STATIC, "config.js"), configJs, "utf-8");

console.log(`build_static: src=${SRC}`);
console.log(`build_static: out=${OUT}`);
console.log(`build_static: POINTSX_API_BASE=${apiBase || "(empty — same-origin)"}`);
